### ISSUE TITLE
Unable to send message

### ISSUE THREAD

**Issue by mxpuck** [therealwolf42/Steem-Chat-Wallet#1]
Hi, I logged in successfully. I tried to message you. When I click "Send" nothing happens.

On a Mac.

**Comment by therealwolf42** [comment]
Is your window empty or filled with Messages from other users like this?

![image](https://user-images.githubusercontent.com/31614097/39663872-e1bbd532-507a-11e8-9bbb-0742d52c7dc0.png)

**Comment by mxpuck** [comment]
I forgot to enter amount of SBD/STEEM. It seems now to default to 0.001 after I entered it once, but it was not working initially.
