### ISSUE TITLE
UI/layout issues after first send

### ISSUE THREAD

**Issue by mxpuck** [therealwolf42/Steem-Chat-Wallet#3]
After sending a message to someone for the first time, the layout is incorrect:

<img width="1017" alt="screen shot 2018-05-07 at 4 53 56 am" src="https://user-images.githubusercontent.com/38818731/39693746-17a7f642-51b3-11e8-9db3-365e5c8ee4f4.png">

**Comment by therealwolf42** [comment]
Should be fixed now.
